name: Push to DockerHub
on: [ push ]
env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
jobs:
  push-to-docker-hub:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, '#test') }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          cache: gradle
      - name: Code build
        run: ./gradlew build --no-daemon -x test -x check
