name: Test against real Lunchmoney API
on: [ push ]
env:
  LUNCHMONEY_TEST_TOKEN: ${{secrets.LUNCHMONEY_TEST_TOKEN}}
jobs:
  test-against-lunchmoney-api:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, '#test') }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          cache: gradle
      - name: Test against real Lunchmoney API
        run: ./gradlew test --no-daemon
